# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DMST Coding Bootcamp
description: > # this means to ignore newlines until "baseurl:"
  This is the site of the Coding Bootcamp organised by the Department
  of Management Science and Technology, Athens University of Economics 
  and Business, Athens, Greece.
baseurl: /coding-bootcamp
# Build settings
markdown: kramdown
